export const BRASILIA_REGIONS = [
  { value: "aguas-claras", label: "Águas Claras" },
  { value: "asa-norte", label: "Asa Norte" },
  { value: "asa-sul", label: "Asa Sul" },
  { value: "brazlandia", label: "Brazlândia" },
  { value: "candangolandia", label: "Candangolândia" },
  { value: "ceilandia-norte", label: "Ceilândia Norte" },
  { value: "ceilandia-sul", label: "Ceilândia Sul" },
  { value: "cruzeiro", label: "Cruzeiro" },
  { value: "fercal", label: "Fercal" },
  { value: "gama", label: "Gama" },
  { value: "guara", label: "Guará" },
  { value: "itapoa", label: "Itapoã" },
  { value: "jardim-botanico", label: "Jardim Botânico" },
  { value: "lago-norte", label: "Lago Norte" },
  { value: "lago-sul", label: "Lago Sul" },
  { value: "nucleo-bandeirante", label: "Núcleo Bandeirante" },
  { value: "paranoa", label: "Paranoá" },
  { value: "park-way", label: "Park Way" },
  { value: "planaltina", label: "Planaltina" },
  { value: "plano-piloto", label: "Plano Piloto" },
  { value: "recanto-das-emas", label: "Recanto das Emas" },
  { value: "riacho-fundo", label: "Riacho Fundo" },
  { value: "riacho-fundo-2", label: "Riacho Fundo II" },
  { value: "samambaia-norte", label: "Samambaia Norte" },
  { value: "samambaia-sul", label: "Samambaia Sul" },
  { value: "santa-maria", label: "Santa Maria" },
  { value: "sao-sebastiao", label: "São Sebastião" },
  { value: "scia", label: "SCIA" },
  { value: "sia", label: "SIA" },
  { value: "sobradinho", label: "Sobradinho" },
  { value: "sobradinho-2", label: "Sobradinho II" },
  { value: "sudoeste", label: "Sudoeste" },
  { value: "taguatinga-centro", label: "Taguatinga Centro" },
  { value: "taguatinga-norte", label: "Taguatinga Norte" },
  { value: "taguatinga-sul", label: "Taguatinga Sul" },
  { value: "varjao", label: "Varjão" },
  { value: "vicente-pires", label: "Vicente Pires" },
];
